### ISSUE TITLE
MissingMethodException on set

### ISSUE THREAD

**Issue by JeremyJeanson** [JustinXinLiu/PullToRefreshUWP_WindowsComposition#1]
When i try to run this sample, i have a strange exception :
"System.MissingMethodException: Méthode introuvable : 'Void Windows.UI.Composition.Visual.put_CenterPoint(System.Numerics.Vector3)'.
   at PullToRefreshXaml.MainPage.<.ctor>b__16_0(Object s, RoutedEventArgs e)"

I have none problems to build it, but i cannot run this sample :(
I have changed nothing.

**Comment by JustinXinLiu** [comment]
Weird. Which version of Windows 10 are you running?

**Comment by JeremyJeanson** [comment]
I found my problem : Visual Studio was broken :(
I repaired it and all work fine yet.
Sorry for this...
