### ISSUE TITLE
Lisence

### ISSUE THREAD

**Issue by MikkoUusitaloSarkain** [JustinXinLiu/PullToRefreshUWP_WindowsComposition#2]
Hello, I cannot find a lisence file or anykind of reference to a lisence. Is this work open source or under what kind of lisence?

**Comment by MikkoUusitaloSarkain** [comment]
Great work by the way!

**Comment by JustinXinLiu** [comment]
Hey thanks! And please feel free to use it in any way you like! No license or whatsoever. :)

**Comment by MikkoUusitaloSarkain** [comment]
Hey, cool thanks!

But I still would prefer somekind of lisence because:

What happens if I don't choose a license?

You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

Even if this is what you intend, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service which do allow other GitHub users some rights. Specifically, you allow others to view and fork your repository within the GitHub site.

If you want others to use, copy, modify, or contribute back to your project, we strongly encourage you to include an open source license.

Source: https://help.github.com/articles/open-source-licensing/

Maybe MIT lisence would be ok?

https://en.wikipedia.org/wiki/MIT_License

**Comment by JustinXinLiu** [comment]
Your right! I just created a MIT one.

**Comment by MikkoUusitaloSarkain** [comment]
Cool Thanks! Keep up the good work :)
